= Flash messages with Turbo Streams (Bootstrap Toast)
:navtitle: Flash/Toast
:imagesdir: ../../images

* Source Repository: {github}
* Bootstrap v5 Toast: https://getbootstrap.com/docs/5.1/components/toasts
* Rails Playground: used in lists on update tasks, not on create/destroy. For create/destroy we use Bootstrap Alert (see xref:flash/index.adoc[])

The goal: show flash messages from turbo_stream via Bootstrap Toast

== Rails controller: set the flash message

./app/controllers/tasks_controller.rb
[source,ruby]
----
def create
  @task = @list.tasks.build(task_params)

  respond_with(@task, location: location) do |format|
    if @task.save
      format.turbo_stream { flash.now[:notice] = "Task successfully created" }
    end
  end
end
----
NOTE: We use `flash.now` here since there is no redirect with turbo_stream.

NOTE: `respond_with` since we uses the `responders` gem from https://github.com/heartcombo/responders. Your mileage may vary. Plain rails 7 generators don't use `respond_to` (nor `respond_with`). See `app/controllers/categories_controller.rb`.

== Layout

Very simple: just a `<div>` with an `id` where to show flash messages from turbo_stream rendering. Otherwise render existing flashes as usual. In case of turbo_stream rendering the content of the `<div>` will be replaced by turbo_stream content.

./app/views/layout/application.html.erb
[source,erb]
----
<div class="container-fluid">
  <div id="flash"> <!--1-->
    <%= render "shared/flash_toast" %>
  </div>
  <%= yield %>
</div>
----
<1> id for turbo_stream replacing

== A Helper to render Turbo Toasts

A helper to call from each `create|update|destroy.turbo_stream.erb` view: simply add the following snippet to each view:

.create|update|destroy.turbo_stream.erb
[source,erb]
----
<%= render_turbo_toast %>
----

See also: https://github.com/swobspace/rails-playground/tree/main/app/views/tasks

=== The helper itself

.app/helpers/flash_toast_helper.rb
[source,ruby]
----
include::example$app/helpers/flash_toast_helper.rb[]
----

=== A partial to go through each flash key

.partial app/views/shared/_flash_toast.html.erb
[source,erb]
----
include::example$app/views/shared/_flash_toast.html.erb[]
----

== A view component for toasts

Since flashes goes with keys like :alert, :error, :notice, we need those translated in Bootstrap jargon like 'danger', 'info' or 'success'.

./app/components/toast_component.rb
[source,ruby]
----
include::example$app/components/toast_component.rb[]
----

./app/components/toast_component.html.erb

[source,erb]
----
include::example$app/components/toast_component.html.erb[]
----

NOTE: `z-index: 2000` to overcome the `z-index` coming with our navbar (`z-index: 1030`)
